import { Footer, Header } from '@/widget'
import type { Metadata } from 'next'
import { Open_Sans, Roboto } from 'next/font/google'
import './globals.css'

export const roboto = Roboto({
	weight: ['400', '700', '900'],
	subsets: ['latin'],
	variable: '--font-roboto',
})

export const open_sans = Open_Sans({
	weight: '400',
	subsets: ['latin'],
	variable: '--font-open-sans',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${open_sans.variable} ${roboto.variable} ${open_sans.className}`}
			>
				<Header />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	)
}
